services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
      # Add build caching
      cache_from:
        - type=registry,ref=node:18-alpine
    ports:
      - "8000:8000"
    volumes:
      - ./output:/app/output
      # Add node_modules volume for faster builds
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 1s
      timeout: 3s
      retries: 30
      start_period: 2s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M

volumes:
  node_modules: # Persistent volume for node_modules 