services:
  app:
    image: concatinate-videos-api:${IMAGE_TAG} # TODO - get this from ECR if not running locally
    ports:
      - "8000:8000"
    volumes:
      - ./output:/app/output:rw
    environment:
      - NODE_ENV=development
    user: "node"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3 


# TODO - merge with other docker compose and add profiles