name: Main Branch Tests

on:
  push:
    branches: [ main, master ]

jobs:
  test:
    strategy:
      matrix:
        node_version: ['16.x', '18.x', '20.x']
    uses: ./.github/workflows/components/test.yml
    with:
      node_version: ${{ matrix.node_version }}
      test_name: 'Main Branch Test - Node ${{ matrix.node_version }}'
      artifact_name: 'test-output-main-${{ matrix.node_version }}'
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        run: echo "Deploy to production"
        # TODO: Add actual deployment steps 