name: Pull Request Checks

on:
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    uses: ./.github/workflows/lint-component.yml
    with:
      node_version: '18.x'
      lint_name: 'PR Lint Check'

  # TODO: Add infrastructure validation job
  # - Validate Terraform configs
  # - Run terraform plan for all environments
  # - Check for drift in existing environments

  # quality:
      # TODO: Add SonarCloud scanning
      # - name: SonarCloud Analysis
      #   uses: SonarSource/sonarcloud-github-action@master
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # TODO: Add Wiz security scanning
      # - name: Wiz Scan
      #   uses: wiz-sec/wiz-cli@v1
      #   with:
      #     auth-token: ${{ secrets.WIZ_TOKEN }}

  test:
    needs: lint
    strategy:
      matrix:
        node_version: ['16.x', '18.x', '20.x'] # TODO: check if needed, based on infrastructure
    uses: ./.github/workflows/test-component.yml
    with:
      node_version: ${{ matrix.node_version }}
      test_name: 'PR Test - Node ${{ matrix.node_version }}'
      artifact_name: 'test-output-pr-${{ matrix.node_version }}'

  security:
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Run security audit
        run: make audit

  #plan-dev:
    # TODO: Add terraform plan job [dev]
    # - Run tf plan for test environment
    # - Save plan artifact for apply job
    # - Post plan summary as PR comment

  #apply-dev:
  # TODO: Add terraform apply job
  # - Requires manual approval
  # - Use saved plan from previous job
  # - Update PR with deployment status 