# TODO- Move deployment automation components into a github-actions/ folder for GHA.

name: Reusable Test Workflow

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
      test_name:
        required: true
        type: string
      artifact_name:
        required: true
        type: string
      snyk_token:
        required: false
        type: string
        default: ''

jobs:
  test:
    name: ${{ inputs.test_name }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and run tests
        run: |
          docker build \
            --build-arg NODE_VERSION=${{ inputs.node_version }} \
            -t concatenate-videos-test-${{ inputs.node_version }} \
            -f Dockerfile.test .
          docker run --rm \
            -v $(pwd)/output:/app/output \
            -e NODE_ENV=test \
            concatenate-videos-test-${{ inputs.node_version }} npm test

      - name: Run security scan
        if: ${{ inputs.node_version == '18.x' && inputs.snyk_token != '' }}
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ inputs.snyk_token }}
        with:
          args: --severity-threshold=high

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: |
            output/
            tests/coverage/
          retention-days: 7 