# TODO- Move deployment automation components into a github-actions/ folder for GHA.

name: Test Component

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
      test_name:
        required: true
        type: string
      artifact_name:
        required: true
        type: string

jobs:
  test:
    name: ${{ inputs.test_name }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          cache: 'npm'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64
          buildkitd-flags: "--debug"
          driver-opts: |
            image=moby/buildkit:master
            network=host

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Install dependencies
        run: |
          npm ci --prefer-offline --no-audit
          cd tests && npm ci --prefer-offline --no-audit

      - name: Run tests
        env:
          JEST_TIMEOUT: 60000  # Reduced timeout
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1
          BUILDKIT_PROGRESS: plain
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: |
          cd tests
          # Run tests with optimizations
          npm test -- \
            --detectOpenHandles \
            --forceExit \
            --testTimeout=60000 \
            --maxWorkers=2 \
            --runInBand \
            --verbose

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: |
            output/
            tests/coverage/
          retention-days: 7 