# TODO- Move deployment automation components into a github-actions/ folder for GHA.

name: Test Component

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
      test_name:
        required: true
        type: string
      artifact_name:
        required: true
        type: string

jobs:
  test:
    name: ${{ inputs.test_name }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and run tests
        run: |
          # Convert version format (e.g., '18.x' to '18')
          NODE_VERSION=$(echo ${{ inputs.node_version }} | cut -d'.' -f1)
          docker build \
            --build-arg NODE_VERSION=$NODE_VERSION \
            -t concatenate-videos-test-${{ inputs.node_version }} \
            -f Dockerfile.test .
          docker run --rm \
            -v $(pwd)/output:/app/output \
            -e NODE_ENV=test \
            concatenate-videos-test-${{ inputs.node_version }} sh -c "cd tests && npm test"

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: |
            output/
            tests/coverage/
          retention-days: 7 